services:
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: portfolio2026
      - key: ADMIN_TOKEN
        value: a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6
      - key: PORTFOLIO_TOKEN
        value: f2ed6d2a9d760bd0dea0a45c
      - key: CLOUDINARY_CLOUD_NAME
        value: fagndkrs
      - key: CLOUDINARY_API_KEY
        value: "377334291729132"
      - key: CLOUDINARY_API_SECRET
        value: rmT5IzAsirbtS8IzEiSJEi2A3O8
